### ISSUE TITLE
[REQ] SRS_Q&A

### ISSUE THREAD

**Issue by tuan0919** [tuan0919/tester-2024#1]
Làm bài tập đầu tiên là tạo SRS cho chức năng mình làm. Mỗi người chọn 1 chức năng để viết SRS cho ổn. Sau đó sẽ tạo ra ít nhất 10 câu hỏi về chức năng của mình.

**Comment by TranVanTrieu21130639** [comment]
[Q&A.docx](https://github.com/user-attachments/files/17435064/Q.A.docx)
[SRS.docx](https://github.com/user-attachments/files/17435065/SRS.docx)
